# Generated by Django 3.0.3 on 2020-02-20 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('executor', models.TextField(blank=True, null=True)),
                ('startDateTime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('endDateTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=64)),
                ('timerTimeFromLastPause', models.DurationField(blank=True, null=True)),
                ('lastStartDateTime', models.DateTimeField(auto_now_add=True)),
                ('timerStatus', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timerStatus'],
            },
        ),
    ]
